name: tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        
    steps:
    - uses: actions/checkout@v4
    
    - name: Install BATS on Ubuntu
      if: runner.os == 'Linux'
      run: sudo apt-get update && sudo apt-get install -y bats-core
      
    - name: Install BATS on macOS
      if: runner.os == 'macOS'
      run: brew install bats-core
    
    - name: Run tests
      run: bats test
      
    - name: Validate POSIX syntax
      run: sh -n log.sh
